name: Security Scan

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:


  CodeQL-Scan:
    name: "CodeQL Scan"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{secrets.DEPLOY_PASSWORD}} | sudo -S chown -R $USER:$USER /home/runner/work/juliet-test-suite

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

#       - name: Autobuild
#         uses: github/codeql-action/autobuild@v1

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '11'
      - name: Build
        run: |
          mvn compile

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v1

  Sonar-Scan:
    name: "Sonar Scan"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{secrets.DEPLOY_PASSWORD}} | sudo -S chown -R $USER:$USER /home/runner/work/juliet-test-suite

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '11'
      - name: Build
        run: |
          mvn compile

      - name: Analyze with SonarCloud
        run: mvn sonar:sonar -Dsonar.projectKey=ghaction-juliet-test-suite -Dsonar.organization=mikomraz -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.scm.disabled=true -Dsonar.cpd.exclusions=** -Dsonar.branch.autoconfig.disabled=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
